version: "3"

services:
  api:
    build: .
    image: messages-api
    ports:
      - 4000:4000
    volumes:
      - ./src:/usr/app/src
    depends_on:
      - db

  db:
    image: mongo
    volumes:
      - ~/data/db:/data/db